name: Deploy Pull Request
on:
  pull_request:

jobs:
  deploy_to_dev:
    uses: ./.github/workflows/DeployEverything.yml
    with:
      env: dev
    secrets: 
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      TERRAFORM_DEPLOYER_APP_ID: ${{ secrets.TERRAFORM_DEPLOYER_APP_ID }}
      TERRAFORM_DEPLOYER_PRIVATE_KEY: ${{ secrets.TERRAFORM_DEPLOYER_PRIVATE_KEY }}
      TERRAFORM_STATE_ACCESS_KEY: ${{ secrets.TERRAFORM_STATE_ACCESS_KEY }}
