name: Deploy Branch Push
on:
  push:
    branches-ignore:
      - 'main'


jobs:
  deploy_to_test:
    uses: ./.github/workflows/DeployEverything.yml
    with:
      env: "Test"
    secrets: 
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      TERRAFORM_STATE_ACCESS_KEY: ${{ secrets.TERRAFORM_STATE_ACCESS_KEY }}
