name: Deploy Pull Request
on:
  pull_request:

jobs:
  deploy_to_dev:
    environment: dev
    uses: ./.github/workflows/DeployEverything.yml
    with:
      env: dev
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}